### PR TITLE
API AssetGalleryField hooks into AssetAdmin search

### PR DESCRIPTION
**Pull request by tractorcow**
See https://github.com/open-sausages/silverstripe-cms/pull/3 for CMS change.

The frontend code will need to be updated; When running the 'search' ajax command, you'll need to either discard or include the `?q=` querystring.

This update ensures that search results are applied correctly to the asset gallery view.

Rather than re-implementing the entire search logic in AssetGalleryField, pre-filtered search results are expected to be injected (yay DI).

Removed all the redundant re-implementation of this search logic.

### CODE REVIEW

**Comment by assertchris** [comment]
Meant to hit comment.

I don't think it's a good idea to merge this without the client side code being fixed and tested.

**Comment by tractorcow** [comment]
Yeah, let's close this and get @flashbackzoo to fix the frontend code before we re-open.

**Comment by flashbackzoo** [comment]
Yup - I can make the changes.

**Comment by assertchris** [comment]
This change does couple the new field with CMS severely. As in no hope of using it with just the ORM, in a non ss project. Don't like that part of it...

**Pull request closed without merging**
